### ISSUE TITLE
Incorrect highlighting of Multiline basic strings

### ISSUE THREAD

**Issue by LeopoldArkham** [bungcip/better-toml#6]
Me again!

Seems the update caused multiline basic strings to highlight incorrectly; use this file to reproduce: https://github.com/LeopoldArkham/Molten/blob/meta/tests/string.toml

These are not big issues at all but at least this way you're aware

**Comment by bungcip** [comment]
thanks for reporting.
I also found out the same issue with datetime and integer using '_'  (ex: 20_0).
